# Title
#### MaryGrace Kane

In [9]:
import pandas as pd

avy_wx = pd.read_pickle('data-prep/pkl/avywx2.pkl')
avy_wx

,avpathid,avobsdate,avobstime,avtype,avtriggertyp,avtrigger,avrelativesize,avdestructivesize,avinterface,sz_vert,...,snowfall_3hr,snowfall_6hr,snowfall_24hr,site,year,sea_lvl_press,sta_press,altimeter_setting,solar_radiation,pct_possible
avrid,,,,,,,,,,,,,,,,,,,,,
1,SHED10,2012-03-26,12:45:00,WS,5.0,NL,R1,D1.5,O,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PATH1163,2012-03-16,08:30:00,U,5.0,NU,U,D2,U,U,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CURLY,2012-03-16,08:34:00,U,5.0,NU,U,D1,U,U,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SHED10,2012-03-10,14:50:00,WL,5.0,NaN,R2,D1,I,M,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,INFINITY,2012-03-10,14:54:00,L,5.0,N,R2,D1,I,T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
504,SHED07W,2022-03-01,05:04:00,SS,5.0,NC,R2,D2,I,T,...,0.0,0.2,11.1,S11MT,2022,NaN,NaN,NaN,NaN,NaN
505,AP1163H,2022-03-23,13:30:00,WL,5.0,NU,R1,D1.5,O,T,...,0.0,0.0,0.0,S11MT,2022,NaN,NaN,NaN,NaN,NaN
506,SHED10,2022-03-23,13:30:00,WL,5.0,N,R2,D2,O,T,...,0.0,0.0,0.0,S11MT,2022,NaN,NaN,NaN,NaN,NaN
507,MCAMSER,2022-03-23,18:00:00,HS,5.0,NC,R3,D3,O,T,...,0.0,0.0,0.0,S11MT,2022,NaN,NaN,NaN,NaN,NaN
508,PATH1163,2022-03-27,14:35:00,WL,5.0,N,R1,D2,O,T,...,0.0,0.0,0.0,S11MT,2022,NaN,NaN,NaN,NaN,NaN

In [10]:
avy_wx.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 491 entries, 1 to 508
Data columns (total 52 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   avpathid           491 non-null    object
 1   avobsdate          491 non-null    datetime64[ns]
 2   avobstime          491 non-null    object
 3   avtype             485 non-null    object
 4   avtriggertyp       455 non-null    float64
 5   avtrigger          446 non-null    object
 6   avrelativesize     474 non-null    object
 7   avdestructivesize  441 non-null    object
 8   avinterface        431 non-null    object
 9   sz_vert            470 non-null    object
 10  sz_horiz           453 non-null    object
 11  sz_avgslope        491 non-null    int64
 12  sz_elev_m          491 non-null    int64
 13  sz_aspect          105 non-null    object
 14  term_elev_m        491 non-null    int64
 15  av_vert_m          491 non-null    int64
 16  crown_width_m      491 non-null    int64
 17  ch_max_cm          491 non-null    int64
 18  ch_min_cm          491 non-null    int64
 19  ch_diff_cm         491 non-null    int64
 20  term_longpath      461 non-null    object
 21  term_shortPath     326 non-null    object
 22  term_detail        307 non-null    object
 23  term_moist         378 non-null    object
 24  deb_rail           491 non-null    bool
 25  deb_rail_w         491 non-null    float64
 26  deb_rail_d         491 non-null    float64
 27  deb_hwy            491 non-null    bool
 28  deb_hwy_w          491 non-null    float64
 29  deb_hwy_d          491 non-null    float64
 30  time               491 non-null    object
 31  dt                 491 non-null    datetime64[ns]
 32  wx_dt              89 non-null     datetime64[ns]
 33  temp               89 non-null     float64
 34  dew_pt             89 non-null     float64
 35  rH                 89 non-null     float64
 36  heat_idx           0 non-null      float64
 37  wind_chill         28 non-null     float64
 38  wind_dir           88 non-null     object
 39  wind_spd           89 non-null     object
 40  hr_precip          0 non-null      float64
 41  snow_depth         89 non-null     float64
 42  snowfall_3hr       89 non-null     float64
 43  snowfall_6hr       89 non-null     float64
 44  snowfall_24hr      87 non-null     float64
 45  site               89 non-null     object
 46  year               89 non-null     object
 47  sea_lvl_press      0 non-null      float64
 48  sta_press          0 non-null      float64
 49  altimeter_setting  0 non-null      float64
 50  solar_radiation    0 non-null      float64
 51  pct_possible       0 non-null      object
dtypes: bool(2), datetime64[ns](3), float64(19), int64(8), object(20)
memory usage: 196.6+ KB